services:
  db:
    container_name: 'db'
    image: postgres:16
    restart: always
    env_file:
      - .env.testing
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - '5432:5432'

  backup:
    build: ./backup
    container_name: backup
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.testing
    volumes:
      - ./pg_backups:/backups
    restart: always
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'test -f /backup.sh && find /backups -type f -mmin -1440 | grep -q .',
        ]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 2m

  redis:
    container_name: 'redis'
    image: redis:7-alpine
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    image: registry.gitlab.com/marjun1988/mj-bookmark-pwa/backend:${VERSION:-latest}
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./favicons:/data/favicons
      - ./nginx/ca-ertificates:/ca-ertificates:ro
    env_file:
      - .env.testing
    #    ports:
    #      - "${BACKEND_PORT}:4000"
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4000/health']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    image: registry.gitlab.com/marjun1988/mj-bookmark-pwa/frontend:${VERSION:-latest}
    restart: always
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      # SSL-Zertifikate ins Container-Verzeichnis einbinden
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/errors:/usr/share/nginx/html/errors:ro
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/index.html']
      interval: 10s
      timeout: 4s
      retries: 5
      start_period: 5s

  vitepress:
    image: registry.gitlab.com/marjun1988/mj-bookmark-pwa/vitepress:${VERSION:-latest}
    restart: always
    volumes:
      - ./vitepress/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/errors:/usr/share/nginx/html/errors:ro
    container_name: vitepress
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/index.html']
      interval: 10s
      timeout: 4s
      retries: 5
      start_period: 5s
