version: '3.3'

services:
  #  phpmayadmin:
  #    container_name: phpmayadmin
  #    image: phpmyadmin/phpmyadmin:latest
  #    # build: ./phpmyadmin/
  #    restart: always
  #    volumes:
  #      #- ./ssl/:/etc/ssl/:ro
  #      - /etc/localtime:/etc/localtime:ro
  #    environment:
  #      - PMA_HOSTS=db
  #      - UPLOAD_LIMIT=300M
  #    ports:
  #      - "8888:80"
  #    depends_on:
  #      - database
  #    links:
  #      - database

  database:
    container_name: database
    image: mysql:8.2.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db/:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --sort_buffer_size=512K
    environment:
      - MYSQL_ROOT_PASSWORD=1i6ra5rskTBVN#t8&?#4
      - MYSQL_DATABASE=mj-bookmark-pwa
      - MYSQL_USER=web-app
      - MYSQL_PASSWORD=oy9xg8x4K4hQXatdytyD

  php-fpm:
    container_name: php-fpm
    image: blackadler/php-fpm-composer:8.2
#    build: ./php-fpm
    restart: always
    volumes:
      - ./:/var/www/
    links:
      - database
    depends_on:
      - database

  nginx:
    container_name: webserver
    build: ./nginx
    restart: always
    volumes:
      - ./:/var/www/
      - ./nginx/logs/:/var/log/nginx
      - ./nginx/ssl/:/etc/ssl/
    ports:
      - "80:80"
      - "443:443"
    links:
      - php-fpm
    depends_on:
      - php-fpm
